export const CART_TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  SUBTRACT_PRODUCT: "SUBTRACT_PRODUCT",
  REMOVE_ONE_PRODUCT: "REMOVE_ONE_PRODUCT",
  REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCTS",
};

export const PRODUCT_FILTER_TYPES = {
  FILTER_PRODUCTS : "FILTER_PRODUCTS",
  RESET_SHOWN_PRODUCTS: "RESET_SHOWN_PRODUCTS",
}

